// front/src/constants/recursosCursos.js

export const CLOUDINARY_IMG_TRANSFORM = 'f_auto,q_auto:best,dpr_auto,w_2200,c_limit';

// IMÁGENES ESTÁTICAS (para TODOS los cursos)
export const IMG_INFO_GENERAL =
    'https://res.cloudinary.com/dx5zamphx/image/upload/v1771342740/informacionGeneral2026_cu.webp';

// Lista de cursos detectados (útil si luego necesitas renderizar un selector)
export const CURSOS_DETECTADOS = [
    "01- 1 MAÑANA",
    "01- 2 MAÑANA",
    "01- 3 TARDE",
    "01- 4 TARDE",
    "02- 1 MAÑANA",
    "02- 2 MAÑANA",
    "02- 3 TARDE",
    "02- 4 TARDE",
    "03- 1 MAÑANA",
    "03- 2 MAÑANA",
    "03- 3 TARDE",
    "03- 4 TARDE",
    "04- 1 MAÑANA",
    "04- 2 MAÑANA",
    "04- 3 TARDE",
    "04- 4 TARDE",
    "05- 1 MAÑANA",
    "05- 2 MAÑANA",
    "05- 3 TARDE",
    "05- 4 TARDE",
    "06 - 1 MAÑANA",
    "06 - 2 TARDE",
    "06 . 1 MAÑANA",
    "06 . 2 TARDE",
    "07 - 1 MAÑANA",
    "07 - 2 TARDE",
    "07 . 1 MAÑANA",
    "07 . 2 TARDE",
    "08 - 1 MAÑANA",
    "08 - 2 TARDE",
    "08 . 1 MAÑANA",
    "08 . 2 TARDE",
    "09 - 1 MAÑANA",
    "09 - 2 TARDE",
    "09 . 1 MAÑANA",
    "09 . 2 TARDE",
    "10 - 1 MAÑANA",
    "10 - 2 TARDE",
    "10 . 1 MAÑANA",
    "10 . 2 TARDE",
    "11 - 1 MAÑANA",
    "11 - 2 TARDE",
    "11 . 1 MAÑANA",
    "JARDIN A MAÑANA",
    "TRANSICION A MAÑANA",
    "TRANSICION B TARDE",
    "TRANSICION C TARDE",
    "11 . 2 TARDE",
    "JARDIN B TARDE",
    "PREJARDIN A MAÑANA"
];

export const VIDEOS_POR_CURSO = {
    "01- 1 MAÑANA": 'https://drive.google.com/file/d/1OcTE7MQMT1JNICChXomuQ7_Mxh9caGT9/preview',
    "01- 2 MAÑANA": 'https://drive.google.com/file/d/1MPVPjU_NzJUuSgRhbt-Kd3wc23WoYcct/preview',
    "01- 3 TARDE": 'https://drive.google.com/file/d/1-2YDgavYqT36ItnpgLxeExmnPhTtco-w/preview',
    "01- 4 TARDE": 'https://drive.google.com/file/d/1o5ELmdllWNJA2P_VCEtgk6Gf8c2oAbnt/preview',
    "02- 1 MAÑANA": 'https://drive.google.com/file/d/1anTxpcuT_rfVG8m7vHg7tnUXw4xNfmT_/preview',
    "02- 2 MAÑANA": 'https://drive.google.com/file/d/1sZrQmB0FpzxV_-QFu65GjMiDnbL8ZOV8/preview',
    "02- 3 TARDE": 'https://drive.google.com/file/d/1sZrQmB0FpzxV_-QFu65GjMiDnbL8ZOV8/preview',
    "02- 4 TARDE": 'https://drive.google.com/file/d/1_3iMfCBcq1O-u3d2gXna1ZWe0uyHqr7r/preview',
    "03- 1 MAÑANA": 'https://drive.google.com/file/d/1_o-BEgbY4lIPXnYwbBt-EAR0Cb1jO1OB/preview',
    "03- 2 MAÑANA": 'https://drive.google.com/file/d/1bjzrxieFN0ClUCVZAIlxYh2z4O8yjXnz/preview',
    "03- 3 TARDE": 'https://drive.google.com/file/d/1_o-BEgbY4lIPXnYwbBt-EAR0Cb1jO1OB/preview',
    "03- 4 TARDE": 'https://drive.google.com/file/d/1qzDGHixEE6JR4_yN53osjmxBi0rZw0Zn/preview',
    "04- 1 MAÑANA": 'https://drive.google.com/file/d/1nNlm1OuvJmJ-W75JXDf8jRO1BKVpGQwz/preview',
    "04- 2 MAÑANA": 'https://drive.google.com/file/d/1KCvYMwGU_7tVOF21upjwn3CtrfTxnJZf/preview',
    "04- 3 TARDE": 'https://drive.google.com/file/d/1nNlm1OuvJmJ-W75JXDf8jRO1BKVpGQwz/preview',
    "04- 4 TARDE": 'https://drive.google.com/file/d/1hiylZuGGyBGPj_k3BJnIqgv1Bw919tty/preview',
    "05- 1 MAÑANA": 'https://drive.google.com/file/d/1RXlxx_Fhspv0pX6a_BcYxGAKvIgZnrDP/preview',
    "05- 2 MAÑANA": 'https://drive.google.com/file/d/1D4G3BXNYs0m3bnDLywY6aNNkZUDpeWk1/preview',
    "05- 3 TARDE": 'https://drive.google.com/file/d/1D4G3BXNYs0m3bnDLywY6aNNkZUDpeWk1/preview',
    "06 1 MAÑANA": 'https://drive.google.com/file/d/1LWpXkPfzfhcaWtxI4XmfUX8r7HH4ghWf/preview',
    "06 2 MAÑANA": 'https://drive.google.com/file/d/114xee6sQ8B8wepfiFR4r60ygk2a-mT--/preview',
    "06 3 TARDE": 'https://drive.google.com/file/d/114xee6sQ8B8wepfiFR4r60ygk2a-mT--/preview',
    "06 4 TARDE": 'https://drive.google.com/file/d/1JtmXLv_6oET4dWwjI8PKYVVE0i6sN1QZ/preview',
    "06 5 TARDE": 'https://drive.google.com/file/d/1iu8M5GfuMZSMSfjj8GT2JI3uguDnBHAc/preview',
    "07 - 1 MAÑANA": 'https://drive.google.com/file/d/1_q820mMUmoEsAQS8kwzZMw-JelBZ6qKG/preview',
    "07 - 2 TARDE": 'https://drive.google.com/file/d/1WhO9fzt4tQSmmadZefPKb99pQFvVK-6c/preview',
    "07 - 3 TARDE": 'https://drive.google.com/file/d/1TyM0XMDR_wt4cO4UOHtcJ7EzDJjD71eW/preview',
    "07. 1 MAÑANA": 'https://drive.google.com/file/d/10Q2ewlv5tmsC84mVHlQuqix-i8F9kp54/preview',
    "07. 2 TARDE": 'https://drive.google.com/file/d/1S-B7FTiTybsgXofg47Cl9BHtmqK2ITmW/preview',
    "08 - 1 MAÑANA": 'https://drive.google.com/file/d/18RtY2pR8FJAdhXbiG6wmCuY7thejwar1/preview',
    "08 - 2 TARDE": 'https://drive.google.com/file/d/1eESjJaupD3UQkt16KIMV6hENauR2FC-W/preview',
    "08 . 1 MAÑANA": 'https://drive.google.com/file/d/1qbc2YGV8zLcQsolA2P6idgCo6_FcJrR-/preview',
    "08 . 2 TARDE": 'https://drive.google.com/file/d/1qbc2YGV8zLcQsolA2P6idgCo6_FcJrR-/preview',
    "09 - 1 MAÑANA": 'https://drive.google.com/file/d/1fRTRY6MvQC2vtN3bUa4_6wgSNlhj_Cl-/preview',
    "09 - 2 TARDE": 'https://drive.google.com/file/d/1Bn1TGixXZXxINNfyXdZ6nbo1Pf95cotD/preview',
    "09 - 3 TARDE": 'https://drive.google.com/file/d/1JiGsZCkg5UJmMQLmjgDuemUnAlHulySu/preview',
    "09 . 1 MAÑANA": 'https://drive.google.com/file/d/1Bn1TGixXZXxINNfyXdZ6nbo1Pf95cotD/preview',
    "09 . 2 MAÑANA": 'https://drive.google.com/file/d/1RHh-5cWhmbJuwZFd6WlRQUtOyQbjHSox/preview',
    "09 . 3 TARDE": 'https://drive.google.com/file/d/1-gKcFkzyzByyOVHYu1gsCEG1QgrtK2Hy/preview',
    "10 - 1 MAÑANA": 'https://drive.google.com/file/d/1OjxzhqK_e8zIKPaLq-dSTKrais61XR79/preview',
    "10 - 2 TARDE": 'https://drive.google.com/file/d/1JKWUcGgUJXI2WshdJA2rvmoZj8q3N0Pr/preview',
    "10 . 1 MAÑANA": 'https://drive.google.com/file/d/1r52LuTzI6J4SnDaLVOmEf82tQw5J8tcR/preview',
    "10 . 2 TARDE": 'https://drive.google.com/file/d/1sXQ0pVCCDnRQnaM6aE2UugZyXbaeJrQS/preview',
    "11 - 1 MAÑANA": 'https://drive.google.com/file/d/1G4gkh3nRQRFXsgNydABvJYrlT2Z_zaxn/preview',
    "11 - 2 TARDE": 'https://drive.google.com/file/d/1Zv49pQ9ql8rsk66R6TeAzMeOWh5r9eV0/preview',
    "11 . 1 MAÑANA": 'https://drive.google.com/file/d/193VmEyiQvVkrnv1gEluZnp6TyH8Lp18r/preview',
};
