export const COORDINATORS = {
  primary: {
    name: 'Diana Díaz',
    area: 'Coordinación Primaria',
    schedules: [
      'Jornada mañana: lunes a viernes, 8:00 a.m. a 10:00 a.m.',
      'Jornada tarde: lunes, martes, miércoles y viernes, 2:30 p.m. a 4:10 p.m.',
      'Jueves en la tarde no atiende.',
    ],
  },
  secondary: {
    name: 'Alexander Fajardo',
    area: 'Coordinación Secundaria',
    schedules: [
      'Jornada mañana: lunes a viernes, 8:00 a.m. a 10:00 a.m.',
      'Jornada tarde: lunes, martes, jueves y viernes, 2:30 p.m. a 4:10 p.m.',
      'Miércoles en la tarde no atiende.',
    ],
  },
};

export const PSYCHOLOGISTS = [
  {
    name: 'Hannyt Kienesberger',
    schedules: [
      'Lunes, martes, miércoles y viernes.',
      'Mañana: 7:00 a.m. a 1:00 p.m.',
      'Tarde: 1:30 p.m. a 5:40 p.m.',
      'Jueves no atiende.',
    ],
    whatsapp: '3175016066',
  },
  {
    name: 'Ángela Ceballos Conde',
    schedules: [
      'Lunes: 9:00 a.m. a 1:00 p.m. y 1:30 p.m. a 3:30 p.m.',
      'Martes: 9:00 a.m. a 1:00 p.m. y 1:30 p.m. a 2:30 p.m.',
      'Miércoles: 9:00 a.m. a 1:00 p.m. y 1:30 p.m. a 3:00 p.m.',
      'Jueves: 9:00 a.m. a 1:00 p.m. y 1:30 p.m. a 3:00 p.m.',
      'Viernes: 9:00 a.m. a 1:00 p.m.',
    ],
    whatsapp: '3175016066',
  },
];

export const TEACHERS = [
  {
    name: 'Angie Rodríguez',
    courses: ['Jardín A', 'Transición B'],
    subjects: [],
    schedules: [
      'Lunes: 8:40 a.m. a 9:10 a.m.',
      'Miércoles: 10:30 a.m. a 11:30 a.m.',
      'Viernes: 1:40 p.m. a 2:30 p.m.',
    ],
  },
  {
    name: 'Lina Sarria',
    courses: ['Transición A'],
    subjects: [],
    schedules: [
      'Miércoles: 7:20 a.m. a 8:15 a.m.',
      'Jueves: 10:30 a.m. a 11:20 a.m.',
    ],
  },
  {
    name: 'Daniela Caicedo',
    courses: ['Primero 2', 'Transición C'],
    subjects: [],
    schedules: [
      'Lunes: 2:30 p.m. a 3:20 p.m.',
      'Miércoles: 8:15 a.m. a 9:10 a.m.',
      'Miércoles: 1:40 p.m. a 2:30 p.m.',
      'Viernes: 9:10 a.m. a 10:00 a.m.',
    ],
  },
  {
    name: 'Ana Elssy Cardona',
    courses: ['Primero 1'],
    subjects: [],
    schedules: [
      'Lunes: 9:10 a.m. a 10:00 a.m.',
      'Martes: 8:15 a.m. a 9:10 a.m.',
      'Jueves: 8:15 a.m. a 9:10 a.m.',
    ],
  },
  {
    name: 'Diana Marcela Gutiérrez',
    courses: ['Primero 4'],
    subjects: [],
    schedules: [
      'Miércoles: 11:30 a.m. a 12:10 p.m.',
      'Miércoles: 12:50 p.m. a 1:40 p.m.',
      'Viernes: 11:30 a.m. a 12:10 p.m.',
    ],
  },
  {
    name: 'Viviana Rojas',
    courses: ['Segundo 1'],
    subjects: [],
    schedules: [
      'Martes: 12:50 p.m. a 1:40 p.m.',
      'Miércoles: 11:30 a.m. a 12:10 p.m.',
      'Viernes: 7:20 a.m. a 8:15 a.m.',
    ],
  },
  {
    name: 'Paola Girón',
    courses: ['Primero 3', 'Tercero 2'],
    subjects: [],
    schedules: [
      'Martes: 12:50 p.m. a 1:40 p.m.',
      'Miércoles: 8:15 a.m. a 9:10 a.m.',
      'Miércoles: 12:50 p.m. a 1:40 p.m.',
      'Viernes: 10:30 a.m. a 11:30 a.m.',
    ],
  },
  {
    name: 'Francy Barona',
    courses: ['Segundo 2', 'Segundo 3'],
    subjects: [],
    schedules: [
      'Lunes: 12:50 p.m. a 1:40 p.m.',
      'Martes: 10:30 a.m. a 11:30 a.m.',
      'Miércoles: 8:20 a.m. a 9:10 a.m.',
      'Viernes: 10:30 a.m. a 11:30 a.m.',
    ],
  },
  {
    name: 'Sharon Castrillon',
    courses: ['Segundo 4'],
    subjects: [],
    schedules: [
      'Lunes: 11:30 a.m. a 12:10 p.m.',
      'Miércoles: 1:40 p.m. a 2:30 p.m.',
    ],
  },
  {
    name: 'Lady Rojas Aranda',
    courses: ['Tercero 1', 'Tercero 3'],
    subjects: [],
    schedules: [
      'Lunes: 8:15 a.m. a 9:10 a.m.',
      'Lunes: 3:20 p.m. a 4:10 p.m.',
      'Miércoles: 9:10 a.m. a 10:00 a.m.',
      'Jueves: 2:30 p.m. a 3:20 p.m.',
      'Viernes: 12:50 p.m. a 1:40 p.m.',
    ],
  },
  {
    name: 'Tulia Muñoz',
    courses: ['3-3', '4-1', '6-3'],
    subjects: ['Inglés', 'Tecnología T-B', 'Tecnología T-C', 'Tecnología 1-3'],
    schedules: [
      'Lunes: 8:30 a.m. a 10:00 a.m.',
      'Jueves: 2:00 p.m. a 3:00 p.m.',
    ],
  },
  {
    name: 'Alexandra Cabal',
    courses: ['Tercero 4', 'Cuarto 2'],
    subjects: [],
    schedules: [
      'Lunes: 7:20 a.m. a 8:15 a.m.',
      'Miércoles: 3:20 p.m. a 4:10 p.m.',
      'Jueves: 11:30 a.m. a 12:00 p.m.',
      'Viernes: 8:15 a.m. a 9:10 a.m.',
      'Viernes: 1:40 p.m. a 2:30 p.m.',
    ],
  },
  {
    name: 'Alexandra Cortés',
    courses: ['Cuarto 1', 'Cuarto 3'],
    subjects: [],
    schedules: [
      'Lunes: 10:30 a.m. a 11:30 a.m.',
      'Miércoles: 11:30 a.m. a 12:00 p.m.',
      'Miércoles: 2:30 p.m. a 3:20 p.m.',
      'Jueves: 4:40 p.m. a 5:40 p.m.',
      'Viernes: 8:15 a.m. a 9:10 a.m.',
    ],
  },
  {
    name: 'Noe Garzon Garzon',
    courses: ['Cuarto 4', 'Quinto 1'],
    subjects: [],
    schedules: [
      'Lunes: 11:30 a.m. a 12:00 p.m.',
      'Martes: 9:10 a.m. a 10:00 a.m.',
      'Jueves: 12:50 p.m. a 2:20 p.m.',
    ],
  },
  {
    name: 'Yimmi Lopez',
    courses: ['Quinto 2', 'Quinto 3'],
    subjects: [],
    schedules: [
      'Martes: 11:30 a.m. a 12:00 p.m.',
      'Martes: 12:50 p.m. a 2:20 p.m.',
      'Viernes: 8:15 a.m. a 9:10 a.m.',
    ],
  },
  {
    name: 'Luz Angela Gasca',
    courses: ['Sexto 1', 'Séptimo 3 COM'],
    subjects: ['Inglés', 'Sociales'],
    schedules: [
      'Lunes: 8:15 a.m. a 9:00 a.m.',
      'Martes: 1:45 p.m. a 2:20 p.m.',
      'Jueves: 7:20 a.m. a 8:10 a.m.',
      'Jueves: 12:45 p.m. a 2:20 p.m.',
      'Viernes: 11:30 a.m. a 12:10 p.m.',
    ],
  },
  {
    name: 'Cielo Espinosa',
    courses: ['Sexto 2', 'Sexto 3'],
    subjects: ['Lengua Castellana'],
    schedules: [
      'Lunes: 8:15 a.m. a 9:50 a.m.',
      'Martes: 10:30 a.m. a 12:10 p.m.',
      'Martes: 7:20 a.m. a 8:10 a.m.',
      'Viernes: 9:10 a.m. a 9:50 a.m.',
    ],
  },
  {
    name: 'John Benitez',
    courses: ['Sexto 4'],
    subjects: ['Artística'],
    schedules: [
      'Martes: 8:15 a.m. a 9:50 a.m.',
      'Martes: 10:25 a.m. a 11:20 a.m.',
      'Miércoles: 12:45 p.m. a 1:30 p.m.',
      'Viernes: 10:25 a.m. a 11:20 a.m.',
      'Viernes: 3:20 p.m. a 4:00 p.m.',
    ],
  },
  {
    name: 'José Donaldo Gutiérrez',
    courses: ['Sexto 5'],
    subjects: ['Ética', 'Religión', 'Cátedra de Paz'],
    schedules: [
      'Lunes: 1:40 p.m. a 2:20 p.m.',
      'Martes: 1:40 p.m. a 2:30 p.m.',
      'Jueves: 10:25 a.m. a 12:10 p.m.',
      'Viernes: 11:30 a.m. a 12:10 p.m.',
      'Viernes: 1:40 p.m. a 2:20 p.m.',
    ],
  },
  {
    name: 'Alejandro Molina',
    courses: ['Séptimo 1 COM', 'Séptimo 2 COM'],
    subjects: ['Ciencias Naturales'],
    schedules: [
      'Lunes: 12:45 p.m. a 1:30 p.m.',
      'Martes: 10:25 a.m. a 11:20 a.m.',
      'Martes: 2:30 p.m. a 3:10 p.m.',
      'Jueves: 1:40 p.m. a 2:20 p.m.',
      'Viernes: 8:15 a.m. a 9:00 a.m.',
      'Viernes: 11:30 a.m. a 12:10 p.m.',
    ],
  },
  {
    name: 'Jorge Ramírez',
    courses: ['Séptimo 1 IND', 'Séptimo 2 IND'],
    subjects: ['Dibujo Técnico', 'Matemáticas'],
    schedules: [
      'Lunes: 12:45 p.m. a 1:30 p.m.',
      'Martes: 11:30 a.m. a 12:10 p.m.',
      'Jueves: 10:25 a.m. a 11:20 a.m.',
      'Jueves: 3:20 p.m. a 4:00 p.m.',
      'Viernes: 8:15 a.m. a 10:00 a.m.',
    ],
  },
  {
    name: 'Viviana Cardoza',
    courses: ['Octavo 1 COM'],
    subjects: ['Inglés'],
    schedules: [
      'Martes: 3:20 p.m. a 4:00 p.m.',
      'Miércoles: 10:25 a.m. a 11:20 a.m.',
      'Jueves: 9:10 a.m. a 10:00 a.m.',
      'Jueves: 11:30 a.m. a 12:10 p.m.',
      'Viernes: 9:10 a.m. a 10:00 a.m.',
      'Viernes: 12:45 p.m. a 1:30 p.m.',
    ],
  },
  {
    name: 'Carolina Peña',
    courses: ['Octavo 1 IND', 'Octavo 2 IND'],
    subjects: ['Matemáticas'],
    schedules: [
      'Martes: 7:20 a.m. a 8:10 a.m.',
      'Miércoles: 9:10 a.m. a 10:00 a.m.',
      'Miércoles: 12:45 p.m. a 2:20 p.m.',
      'Jueves: 8:15 a.m. a 9:00 a.m.',
      'Jueves: 3:20 p.m. a 4:00 p.m.',
    ],
  },
  {
    name: 'Mauricio Méndez',
    courses: ['Octavo 2 COM'],
    subjects: ['Lengua Castellana'],
    schedules: [
      'Lunes: 9:10 a.m. a 10:00 a.m.',
      'Martes: 2:30 p.m. a 4:00 p.m.',
      'Miércoles: 11:30 a.m. a 12:10 p.m.',
      'Jueves: 2:30 p.m. a 3:10 p.m.',
      'Viernes: 6:20 a.m. a 7:10 a.m.',
    ],
  },
  {
    name: 'Luis E. Villalba',
    courses: ['Noveno 1 COM', 'Décimo 2 COM'],
    subjects: ['Modalidad Comercial'],
    schedules: [
      'Lunes: 7:20 a.m. a 9:00 a.m.',
      'Lunes: 12:45 p.m. a 2:20 p.m.',
      'Martes: 9:10 a.m. a 10:00 a.m.',
      'Jueves: 10:25 a.m. a 11:20 a.m.',
    ],
  },
  {
    name: 'John Alegrias',
    courses: ['Noveno 1 IND', 'Noveno 2 COM'],
    subjects: ['Ciencias Sociales', 'Filosofía'],
    schedules: [
      'Lunes: 2:30 p.m. a 3:10 p.m.',
      'Martes: 2:30 p.m. a 3:10 p.m.',
      'Miércoles: 10:25 a.m. a 11:20 a.m.',
      'Viernes: 8:15 a.m. a 10:00 a.m.',
      'Viernes: 2:30 p.m. a 3:10 p.m.',
    ],
  },
  {
    name: 'Salome Espinosa',
    courses: ['Noveno 3 COM'],
    subjects: ['Inglés'],
    schedules: [
      'Lunes: 2:30 p.m. a 3:10 p.m.',
      'Miércoles: 8:15 a.m. a 9:00 a.m.',
      'Miércoles: 4:35 p.m. a 5:30 p.m.',
      'Viernes: 6:20 a.m. a 8:10 a.m.',
    ],
  },
  {
    name: 'Monica Montoya',
    courses: ['Décimo 1 COM'],
    subjects: ['Lengua Castellana'],
    schedules: [
      'Lunes: 10:25 a.m. a 11:20 a.m.',
      'Lunes: 12:45 p.m. a 1:30 p.m.',
      'Lunes: 3:20 p.m. a 4:00 p.m.',
      'Viernes: 10:25 a.m. a 12:10 p.m.',
      'Viernes: 12:45 p.m. a 1:30 p.m.',
    ],
  },
  {
    name: 'Olmes Gordillo',
    courses: ['Décimo 1 IND'],
    subjects: ['Modalidad Industrial'],
    schedules: [
      'Lunes: 7:20 a.m. a 8:10 a.m.',
      'Martes: 9:10 a.m. a 10:00 a.m.',
      'Martes: 1:40 p.m. a 2:20 p.m.',
      'Miércoles: 6:20 a.m. a 7:10 a.m.',
      'Jueves: 3:20 p.m. a 4:00 p.m.',
      'Viernes: 8:15 a.m. a 9:00 a.m.',
    ],
  },
  {
    name: 'Elizabeth Borelly',
    courses: ['Once 1 COM', 'Décimo 2 IND'],
    subjects: ['Ética', 'Religión', 'Cátedra de Paz'],
    schedules: [
      'Lunes: 3:20 p.m. a 4:00 p.m.',
      'Lunes: 4:35 p.m. a 5:30 p.m.',
      'Miércoles: 1:40 p.m. a 2:20 p.m.',
      'Viernes: 7:20 a.m. a 9:00 a.m.',
      'Viernes: 11:30 a.m. a 12:10 p.m.',
    ],
  },
  {
    name: 'Ricardo Gerena',
    courses: ['Noveno 2 IND', 'Once 2 IND'],
    subjects: ['Educación Física'],
    schedules: [
      'Martes: 10:25 a.m. a 11:20 a.m.',
      'Jueves: 10:25 a.m. a 11:20 a.m.',
      'Viernes: 7:20 a.m. a 8:10 a.m.',
      'Viernes: 10:25 a.m. a 11:20 a.m.',
      'Viernes: 1:40 p.m. a 2:20 p.m.',
      'Viernes: 4:35 p.m. a 5:30 p.m.',
    ],
  },
  {
    name: 'Olga Lucia Pacheco',
    courses: ['Once 1 IND'],
    subjects: ['Ciencias Sociales', 'Ética', 'Ciencia y Tecnología'],
    schedules: [
      'Martes: 1:40 p.m. a 2:20 p.m.',
      'Jueves: 11:30 a.m. a 12:10 p.m.',
      'Jueves: 1:40 p.m. a 3:10 p.m.',
      'Viernes: 7:20 a.m. a 8:10 a.m.',
      'Viernes: 9:10 a.m. a 10:00 a.m.',
    ],
  },
  {
    name: 'Jose Angel',
    courses: ['Noveno 3 IND'],
    subjects: ['Matemáticas', 'Física'],
    schedules: [
      'Lunes: 9:10 a.m. a 10:00 a.m.',
      'Lunes: 11:30 a.m. a 12:20 p.m.',
      'Lunes: 1:40 p.m. a 3:10 p.m.',
      'Martes: 11:30 a.m. a 12:10 p.m.',
      'Miércoles: 3:20 p.m. a 4:00 p.m.',
    ],
  },
  {
    name: 'Roosevel Lopez',
    courses: [],
    subjects: ['Bio-Química'],
    schedules: [
      'Lunes: 10:25 a.m. a 11:20 a.m.',
      'Lunes: 1:40 p.m. a 2:20 p.m.',
      'Miércoles: 7:20 a.m. a 8:10 a.m.',
      'Miércoles: 10:25 a.m. a 11:20 a.m.',
      'Jueves: 12:45 p.m. a 1:30 p.m.',
      'Viernes: 6:20 a.m. a 7:10 a.m.',
    ],
  },
  {
    name: 'Ivan Pardo',
    courses: [],
    subjects: ['Informática'],
    schedules: [
      'Lunes: 7:20 a.m. a 8:10 a.m.',
      'Lunes: 10:25 a.m. a 11:20 a.m.',
      'Miércoles: 7:20 a.m. a 8:10 a.m.',
      'Jueves: 9:10 a.m. a 10:00 a.m.',
      'Viernes: 6:20 a.m. a 7:10 a.m.',
    ],
  },
  {
    name: 'Gustavo García',
    courses: [],
    subjects: ['Educación Física', 'Ciencias Naturales'],
    schedules: [
      'Martes: 9:10 a.m. a 10:00 a.m.',
      'Martes: 1:40 p.m. a 2:20 p.m.',
      'Miércoles: 10:30 a.m. a 11:20 a.m.',
      'Jueves: 8:15 a.m. a 9:00 a.m.',
      'Jueves: 12:45 p.m. a 1:30 p.m.',
      'Viernes: 12:45 p.m. a 1:30 p.m.',
    ],
  },
];

export const GROUP_DIRECTORS = [
  { course: 'Jardín A', teacher: 'Angie Rodríguez' },
  { course: 'Transición A', teacher: 'Lina Sarria' },
  { course: 'Transición B', teacher: 'Angie Rodríguez' },
  { course: 'Transición C', teacher: 'Daniela Caicedo' },
  { course: 'Primero 1', teacher: 'Ana Elssy Cardona' },
  { course: 'Primero 2', teacher: 'Daniela Caicedo' },
  { course: 'Primero 3', teacher: 'Paola Girón' },
  { course: 'Primero 4', teacher: 'Diana Marcela Gutiérrez' },
  { course: 'Segundo 1', teacher: 'Viviana Rojas' },
  { course: 'Segundo 2', teacher: 'Francy Barona' },
  { course: 'Segundo 3', teacher: 'Francy Barona' },
  { course: 'Segundo 4', teacher: 'Sharon Castrillon' },
  { course: 'Tercero 1', teacher: 'Lady Rojas Aranda' },
  { course: 'Tercero 2', teacher: 'Paola Girón' },
  { course: 'Tercero 3', teacher: 'Lady Rojas Aranda' },
  { course: 'Tercero 4', teacher: 'Alexandra Cabal' },
  { course: 'Cuarto 1', teacher: 'Alexandra Cortés' },
  { course: 'Cuarto 2', teacher: 'Alexandra Cabal' },
  { course: 'Cuarto 3', teacher: 'Alexandra Cortés' },
  { course: 'Cuarto 4', teacher: 'Noe Garzon Garzon' },
  { course: 'Quinto 1', teacher: 'Noe Garzon Garzon' },
  { course: 'Quinto 2', teacher: 'Yimmi Lopez' },
  { course: 'Quinto 3', teacher: 'Yimmi Lopez' },
  { course: 'Sexto 1', teacher: 'Luz Angela Gasca' },
  { course: 'Sexto 2', teacher: 'Cielo Espinosa' },
  { course: 'Sexto 3', teacher: 'Cielo Espinosa' },
  { course: 'Sexto 4', teacher: 'John Benitez' },
  { course: 'Sexto 5', teacher: 'José Donaldo Gutiérrez' },
  { course: 'Séptimo 1 COM', teacher: 'Alejandro Molina' },
  { course: 'Séptimo 2 COM', teacher: 'Alejandro Molina' },
  { course: 'Séptimo 3 COM', teacher: 'Luz Angela Gasca' },
  { course: 'Séptimo 1 IND', teacher: 'Jorge Ramírez' },
  { course: 'Séptimo 2 IND', teacher: 'Jorge Ramírez' },
  { course: 'Octavo 1 COM', teacher: 'Viviana Cardoza' },
  { course: 'Octavo 2 COM', teacher: 'Mauricio Méndez' },
  { course: 'Octavo 1 IND', teacher: 'Carolina Peña' },
  { course: 'Octavo 2 IND', teacher: 'Carolina Peña' },
  { course: 'Noveno 1 COM', teacher: 'Luis E. Villalba' },
  { course: 'Noveno 2 COM', teacher: 'John Alegrias' },
  { course: 'Noveno 3 COM', teacher: 'Salome Espinosa' },
  { course: 'Noveno 1 IND', teacher: 'John Alegrias' },
  { course: 'Noveno 2 IND', teacher: 'Ricardo Gerena' },
  { course: 'Noveno 3 IND', teacher: 'Jose Angel' },
  { course: 'Décimo 1 COM', teacher: 'Monica Montoya' },
  { course: 'Décimo 2 COM', teacher: 'Luis E. Villalba' },
  { course: 'Décimo 1 IND', teacher: 'Olmes Gordillo' },
  { course: 'Décimo 2 IND', teacher: 'Elizabeth Borelly' },
  { course: 'Once 1 COM', teacher: 'Elizabeth Borelly' },
  { course: 'Once 2 COM', teacher: 'John Alegrias' },
  { course: 'Once 1 IND', teacher: 'Olga Lucia Pacheco' },
  { course: 'Once 2 IND', teacher: 'Ricardo Gerena' },
];
